package org.soapbuilder;


/**
 * Java Bean: EndpointInfo
 *    for Web service proxy: interopInfoSvcProxy
 *    generated by Oracle WSDL toolkit (Version: 1.0).
 */
public class EndpointInfo {

    public EndpointInfo() {

    }

    public EndpointInfo(java.lang.String _endpointName, java.lang.String _endpointURL, java.lang.String _wsdlURL) {
        m_endpointName = _endpointName;
        m_endpointURL = _endpointURL;
        m_wsdlURL = _wsdlURL;

    }

    public java.lang.String getEndpointName() {
        return m_endpointName;

    }

    public void setEndpointName(java.lang.String _endpointName) {
        m_endpointName = _endpointName;

    }

    public java.lang.String getEndpointURL() {
        return m_endpointURL;

    }

    public void setEndpointURL(java.lang.String _endpointURL) {
        m_endpointURL = _endpointURL;

    }

    public java.lang.String getWsdlURL() {
        return m_wsdlURL;

    }

    public void setWsdlURL(java.lang.String _wsdlURL) {
        m_wsdlURL = _wsdlURL;

    }


    private java.lang.String m_endpointName;
    private java.lang.String m_endpointURL;
    private java.lang.String m_wsdlURL;

}
