package org.soapbuilder;

import java.util.Vector;
import java.net.URL;
import java.util.Properties;
import java.util.HashMap;
import org.apache.soap.rpc.Call;
import org.apache.soap.rpc.Parameter;
import org.apache.soap.rpc.Response;
import org.apache.soap.Fault;
import org.apache.soap.SOAPException;
import org.apache.soap.Constants;
import org.apache.soap.encoding.SOAPMappingRegistry;
import org.apache.soap.encoding.soapenc.BeanSerializer;
import org.apache.soap.util.xml.QName;
import oracle.soap.transport.http.OracleSOAPHTTPConnection;
import oracle.soap.encoding.soapenc.EncUtils;

/**
 * Web service proxy: interopInfoSvc
 *     generated by Oracle WSDL toolkit (Version: 1.0).
 * The code generated has been modify to support complext types with
 * multiple untyped parts.
 */
public class interopInfoSvcProxy {

    public interopInfoSvcProxy() {
        m_httpConnection = new OracleSOAPHTTPConnection();
        _setMaintainSession(true);
        m_soapMappingRegistry = new SOAPMappingRegistry();

        // Register a custom deserializer to handle EndpointInfo[] with untyped parts.
        // note: the generated code has been removed to enhance readability.
        EndpointInfoArrayDeserializer eiaDes = new EndpointInfoArrayDeserializer();
        m_soapMappingRegistry.mapTypes(
            Constants.NS_URI_SOAP_ENC, new QName("", "return"), 
            org.soapbuilder.EndpointInfo.class, null, eiaDes);
    }

    public org.soapbuilder.EndpointInfo[] GetEndpointInfo(java.lang.String groupName) throws Exception {
        String soapActionURI = "http://soapinterop.org/info/";
        String encodingStyleURI = "http://schemas.xmlsoap.org/soap/encoding/";
        Vector params = new Vector();
        params.add(new Parameter("groupName", java.lang.String.class, groupName, null));
        Response response = makeSOAPCallRPC("GetEndpointInfo", params, encodingStyleURI, soapActionURI);
        Parameter returnValue = response.getReturnValue();
        return (org.soapbuilder.EndpointInfo[])returnValue.getValue();
    }

    private Response makeSOAPCallRPC(String methodName, Vector params, String encodingStyleURI, String soapActionURI) throws Exception {
        Call call  = new Call();
        call.setSOAPTransport(m_httpConnection);
        call.setSOAPMappingRegistry(m_soapMappingRegistry);
        call.setTargetObjectURI(m_serviceID);
        call.setMethodName(methodName);
        call.setEncodingStyleURI(encodingStyleURI);
        call.setParams(params);

        Response response = call.invoke(new URL(m_soapURL), soapActionURI);
        if (response.generatedFault()) {
            Fault fault = response.getFault();
            throw new SOAPException(fault.getFaultCode(), fault.getFaultString());
        }
        return response;
    }

    public String _getSoapURL() {
        return m_soapURL;
    }

    public void _setSoapURL(String soapURL) {
        m_soapURL = soapURL;
    }

    public String _getServiceID() {
        return m_serviceID;
    }

    public void _setServiceID(String serviceID) {
        m_serviceID = serviceID;
    }

    public SOAPMappingRegistry _getSOAPMappingRegistry() {
        return m_soapMappingRegistry;
    }

    public void _setSOAPMappingRegistry(SOAPMappingRegistry soapMappingRegistry) {
        m_soapMappingRegistry = soapMappingRegistry;
    }

    public boolean _getMaintainSession() {
        return m_httpConnection.getMaintainSession();
    }

    public void _setMaintainSession(boolean maintainSession) {
        m_httpConnection.setMaintainSession(maintainSession);
    }

    public Properties _getTransportProperties() {
        return m_httpConnection.getProperties();
    }

    public void _setTransportProperties(Properties properties) {
        m_httpConnection.setProperties(properties);
    }

    public String _getVersion() {
        return m_version;
    }

    private String m_serviceID = "http://soapinterop.org/info/";
    private String m_soapURL = "http://www.whitemesa.net/interopInfo";
    private OracleSOAPHTTPConnection m_httpConnection = null;
    private SOAPMappingRegistry m_soapMappingRegistry = null;
    private String m_version = "1.0";

}
