package oracle.j2ee.ws_example;
/**
 * Generated by the Oracle9i JDeveloper Web Services Stub/Skeleton Generator.
 * Date Created: Wed Feb 27 14:12:55 PST 2002
 * WSDL URL: file:/D:/DevRoot/interop/InteropEndpoints/public_html/wsdl/Import1.wsdl
 */

public class Import1Service
{
  public String echoString(String x) throws Exception
  {
    return x;
  }
}