package oracle.j2ee.ws_example;
/**
 * Generated by the Oracle9i JDeveloper Web Services Stub/Skeleton Generator.
 * Date Created: Wed Feb 27 14:40:24 PST 2002
 * WSDL URL: file:/D:/DevRoot/interop/InteropEndpoints/public_html/wsdl/Import3.wsdl
 */

public class Import3Service 
{
  public SOAPStruct[] echoStructArray(SOAPStruct[] inputArray) throws Exception
  {
    return inputArray;
  }

  public SOAPStruct echoStruct(SOAPStruct inputStruct) throws Exception
  {
    return inputStruct;
  }
}