package oracle.j2ee.ws_example;
/**
 * Generated by the Oracle9i JDeveloper Web Services Stub/Skeleton Generator.
 * Date Created: Wed Feb 27 14:26:32 PST 2002
 * WSDL URL: file:/D:/DevRoot/interop/InteropEndpoints/public_html/wsdl/Import2.wsdl
 */

public class Import2Service 
{
  public SOAPStruct echoStruct(SOAPStruct inputStruct) throws Exception
  { 
    return inputStruct;
  }
}