package oracle.j2ee.ws_example;

/**
 * Generated by the Oracle9i JDeveloper Web Services Stub/Skeleton Generator.
 * Date Created: Wed Feb 20 18:30:44 PST 2002
 * 
 * <complexType name="SOAPStruct">
 * <all>
 * <element name="varFloat" type="xsd:float"/>
 * <element name="varInt" type="xsd:int"/>
 * <element name="varString" type="xsd:string"/>
 * </all>
 * </complexType>
 */

public class SOAPStruct 
{
  private String m_varString;

  private Integer m_varInt;

  private Float m_varFloat;

  public SOAPStruct()
  {
  }

  public SOAPStruct(String varString, Integer varInt, Float varFloat)
  {
    m_varString = varString;
    m_varInt = varInt;
    m_varFloat = varFloat;
  }

  public void setVarString(String varString)
  {
    m_varString = varString;
  }

  public String getVarString()
  {
    return m_varString;
  }

  public void setVarInt(Integer varInt)
  {
    m_varInt = varInt;
  }

  public Integer getVarInt()
  {
    return m_varInt;
  }

  public void setVarFloat(Float varFloat)
  {
    m_varFloat = varFloat;
  }

  public Float getVarFloat()
  {
    return m_varFloat;
  }

  /**
   * Equality comparison.  
   */
  public boolean equals(Object object) 
  {
     if (!(object instanceof SOAPStruct)) 
       return false;

     SOAPStruct that = (SOAPStruct) object;

     if (!this.m_varInt.equals(that.m_varInt)) 
       return false;

     if (!this.m_varFloat.equals(that.m_varFloat)) 
       return false;

     if (this.m_varString == null) {
       if (that.m_varString != null) 
         return false;
     } else {
       if (!this.m_varString.equals(that.m_varString)) 
         return false;
     }
     return true;
  }

  /**
   * Printable representation
   */
  public String toString() 
  {
    return "{" + m_varFloat + ", " + m_varInt + ", '" + m_varString + "'}";
  }
}